name: Deploy Website Content

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"

env:
  AWS_REGION: #eg. eu-west-2
  S3_WEBSITE_BUCKET: website-bucket

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::YOUR_ACCOUNT_ID:role/YOUR_ROLE_NAME
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync src/ s3://${{env.S3_WEBSITE_BUCKET}}/ --delete
