name: Terraform CI

on:
  workflow_dispatch:
  push:
    paths:
      - "terraform/**"
  pull_request:
    paths:
      - "terraform/**"

env:
  AWS_REGION: #eg. eu-west-2

jobs:
  terraform:
    name: "Terraform CI"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.2

      - name: Terraform Init
        working-directory: ${{ github.workspace }}/terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ github.workspace }}/terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ github.workspace }}/terraform
        run: terraform plan
